default: &default
  audio_bucket_region: "ap-southeast-1"
  audio_bucket: "<%= ENV.fetch('AUDIO_BUCKET', 'audio.open-ews.org') %>"
  open_ews_host: "https://api.open-ews.org"

production: &production
  <<: *default
  sentry_dsn: "<%= app_settings.credentials.fetch('sentry_dsn') %>"
  open_ews_accounts: <%= app_settings.credentials.fetch('open_ews_accounts').to_yaml %>

staging:
  <<: *production

development: &development
  <<: *default
  open_ews_accounts:
    ews_1294_cambodia:
      api_key: "secret"

test: &test
  <<: *development
