default: &default
  audio_bucket_region: "ap-southeast-1"
  audio_bucket: "<%= ENV.fetch('AUDIO_BUCKET', 'audio.open-ews.org') %>"

production: &production
  <<: *default
  sentry_dsn: "<%= app_settings.credentials.fetch('sentry_dsn') %>"

staging:
  <<: *production

development: &development
  <<: *default

test: &test
  <<: *development
