default: &default
  audio_host: "<%= ENV.fetch('AUDIO_HOST', 'https://uploads.open-ews.org') %>"
  open_ews_host: "<%= ENV.fetch('OPEN_EWS_HOST', 'https://api.open-ews.org') %>"
  app_version: "<%= ENV.fetch('APP_VERSION', '0.0') %>"
  app_source: "<%= ENV.fetch('APP_SOURCE', 'https://github.com/open-ews/open-ews-ivr') %>"

production: &production
  <<: *default
  sentry_dsn: "<%= app_settings.credentials.fetch('sentry_dsn') %>"
  open_ews_accounts:
    ews_1294_cambodia:
      api_key: "<%= app_settings.credentials.dig('open_ews_accounts', 'ews_1294_cambodia', 'api_key') %>"

staging:
  <<: *production

development: &development
  <<: *default
  open_ews_accounts:
    ews_1294_cambodia:
      api_key: "secret"

test: &test
  <<: *development
