name: Cleanup Packages

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  cleanup_packages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'open-ews-ivr'
          package-type: 'container'
          delete-only-untagged-versions: 'true'
